name: "EVN VN"
description: "Add-on EVN VN in Home Assistant"
url: "https://github.com/smarthomeblack/hass-addon"
version: "2025.10.30"
slug: "evnvn"
init: false
ingress: true
ingress_port: 1093
panel_icon: mdi:transmission-tower-import
map:
  - config:rw
  - data:rw
options:
  accounts_json: >
    [
      {"userevn": "tài khoản evn", "passevn": "mật khẩu evn", "server": "npc"}
    ]
  gemini_api_key: "API_KEY"
  gemini_model: "gemini-2.0-flash"
  threadId: "123456789"
  type: "group"
  accountSelection: "+84999999999"
  urlzalo: "http://192.168.1.22:3000"
  telegram_token: ""
  telegram_chat_id: ""
  telegram_thread_id: 0
host_network: true
hassio_api: true
hassio_role: "admin"
ports:
  1093/tcp: null
schema:
  accounts_json: str
  gemini_api_key: str
  gemini_model: str
  threadId: str?
  type: str?
  accountSelection: str?
  urlzalo: str?
  telegram_token: str?
  telegram_chat_id: str?
  telegram_thread_id: int?

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
image: "ghcr.io/smarthomeblack/evnvn-{arch}"
